language: node_js
node_js:
  - '5.0'
  - '5.6'

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - bower_components
    - node_modules

env:
  matrix:
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-1-13
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: "SYF34alow+5UDRfeKp7KNH+IHJy/pvW/948uRRPB61IlLmlGZDKP5Zw/PDem/ndAa4Jum04a+SKa6EN0P3ZfxvNwlZq81IeRd8Xd3hot/DaSzv52IjKk1gA7mq8/zuRGJMc5BkmaqMM3rgOwZzLQl2VrdWqtE5Rh2fbGirnDp5dH6E3T9+hNTo49pD8S22npWeWLmH93ipZt1dVTjxWaNp+PsP3LXnH6c5/GCIweREgnUaug4er/Iuzb3VaXCXEM0lUzmGipa3l8p6Fkp01nMGy28NYkdyFT3WoXVK2cYS1HBx7aCGn46jpGaSxCT84J98qZDs3LLMxX9ICtcBYa7+LE4jKe/zpjkdQQXOi8+0eJKeAvPPNzdUrTtupgDf9WN63qwL3vrh9HEy9yLRCjayuj7l8KKeKsqXko58Fp0Dr80KCm9e7+xB8oi/zHX2qPJDKD1DXQSzeWX4bkiNZBaKrlgaaS3Ad8DVeuyIJjun/7OPfKLvFg9htMKsqXyE6dNmK4t5YPSBMDVlb4q1OFwtsluMDf2lhaj3KEixUA+cAxyyBLKvuQl1NPeWs/C5ryLv2/U/6s/LkIHEVQMF0f27RDVCeHrGJv+r6z7TtesXwEdiSo/mLYCIxfndWMF4sW5C5rgDs744/wS1ZX1Eni8CLlxxBGonaJiOW70AV3t2c="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g pr-bumper
  - pr-bumper check

install:
  - npm install
  - bower install

script:
  - npm run lint
  - ember try $EMBER_TRY_SCENARIO test

before_deploy:
  - pr-bumper bump

deploy:
  provider: npm
  email: dahl.matthew@gmail.com
  skip_cleanup: true
  api_key:
    secure: X8R9zeYnrNGnylJ7erwIFnCcuk7QcdtxB+HgR8RL+KtxeDwBCprsAP3/MR7HARVTjIoOxdlNT4EQ4qOKLhOrzaaIivKw8WABRYRao17cDWJNUqo+QZ/bRdSUjhlu/B1iTWhiXLVZYYfkAcM6RHOvZq6n/7Mv3SQsvi/y8H8K6VcsC2RcxG+vX1Je1KT8OJubWz5LmGwIq7EbFMv0GQkhGVoOrSpWpZDIIlnSdvsx/OPW0oCWfmdQ8zOe75ipszrLGlZkGPd1SlnQ+mR3mipHQ41wg7Mq7NwY6VEIbTFHdvHDjgpdaH4rz3bzQmHZUeFe0ypccgcjSdawIWV22y2mmU7y3B6PddiiN6ori7tPcIpAe6fQMUXFojs8a9Xj252YDnf9sPL0gok9MhXEIwPGpnAnDn4he1vpniMQql7CcfisXpn/CGCbKJxgbpIxMDM6jTeFVMoyy+uBXZhL2py7CFoJSWKNSxW2pTXJvm4yCBHdmVwRbkJ0sGr+BPsww4idJ79F5gKA2tW/WY89dbAzp4k3QSoQ0azEDGW1J60kSqS1igKbDnjjG/7atUm7m9I36GSmEHyjqU218+/dsRIChZSvBCcGWgDoK8zh/4EoJ8oed2bryiglwHexBnwrOD4IPkDfCfw16LnnLj/w2kvi226DpVcoqRyUbfqqlZVdU9M=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '5.6'
    tags: false
